#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 002: Implement Configurable Logging System

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Project: Thunderbird Email AI Assistant"
echo "Feature: Configurable Logging System"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project root
PROJECT_ROOT="/home/titus/Projects/thunderbird-email-ai-assistant"
cd "$PROJECT_ROOT"

echo ""
echo "Project Type: Single-service TypeScript browser extension"
echo "Tech Stack: TypeScript + Webpack + tsyringe DI + Vitest"
echo ""

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo "========================================"
echo "Installing Dependencies"
echo "========================================"

if [ ! -d "node_modules" ]; then
    echo "Installing npm packages..."
    npm install
    echo -e "${GREEN}Dependencies installed${NC}"
else
    echo -e "${GREEN}Dependencies already installed${NC}"
fi

# ============================================
# RUN TYPE CHECK
# ============================================

echo ""
echo "========================================"
echo "Running Type Check"
echo "========================================"

npm run type-check
if [ $? -eq 0 ]; then
    echo -e "${GREEN}Type check passed${NC}"
else
    echo -e "${RED}Type check failed${NC}"
    exit 1
fi

# ============================================
# RUN TESTS
# ============================================

echo ""
echo "========================================"
echo "Running Tests"
echo "========================================"

npm test
if [ $? -eq 0 ]; then
    echo -e "${GREEN}All tests passed${NC}"
else
    echo -e "${YELLOW}Some tests failed (expected during development)${NC}"
fi

# ============================================
# BUILD EXTENSION
# ============================================

echo ""
echo "========================================"
echo "Building Extension"
echo "========================================"

npm run build:dev
if [ $? -eq 0 ]; then
    echo -e "${GREEN}Build successful${NC}"
else
    echo -e "${RED}Build failed${NC}"
    exit 1
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Project: Thunderbird Email AI Assistant"
echo "Feature: Configurable Logging System"
echo ""
echo "Next Steps:"
echo "  1. Load extension in Thunderbird:"
echo "     - Tools -> Add-ons and Themes -> Gear icon -> Debug Add-ons"
echo "     - Click 'Load Temporary Add-on' and select manifest.json"
echo ""
echo "  2. Open Browser Console:"
echo "     - Tools -> Developer Tools -> Error Console (Ctrl+Shift+J)"
echo ""
echo "  3. Open Settings Page:"
echo "     - In Thunderbird: Tools -> Add-ons -> Extensions -> Settings"
echo "     - Or directly: moz-extension://<id>/options.html"
echo ""
echo "Available Commands:"
echo "  npm run build:dev    - Development build with watch mode"
echo "  npm run build        - Production build"
echo "  npm run test         - Run all tests"
echo "  npm run test:watch   - Run tests in watch mode"
echo "  npm run type-check   - TypeScript type checking"
echo "  npm run lint         - Run ESLint"
echo "  npm run package      - Package extension as .zip"
echo ""
echo "Log Levels: DEBUG, INFO, WARN, ERROR"
echo "Default: INFO"
echo ""
